apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oversea-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oversea-server
  template:
    metadata:
      labels:
        app: oversea-server
    spec:
      containers:
      - name: server
        image: us-west1-docker.pkg.dev/cs144-25s-jlin18/oversea-app/oversea-server:v1
        ports: 
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: MONGO_URI 
        - name: ACCESS_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: ACCESS_TOKEN_SECRET 
        - name: REFRESH_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: REFRESH_TOKEN_SECRET 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oversea-ai-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oversea-ai-service
  template:
    metadata:
      labels:
        app: oversea-ai-service
    spec:
      containers:
      - name: ai-service
        image: us-west1-docker.pkg.dev/cs144-25s-jlin18/oversea-app/oversea-ai-service:v1
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: MONGO_URI 
        - name: AZURE_OPENAI_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: AZURE_OPENAI_ENDPOINT 
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: AZURE_OPENAI_API_KEY 
        - name: AZURE_OPENAI_API_VERSION
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: AZURE_OPENAI_API_VERSION 
        - name: AZURE_SEARCH_SERVICE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: AZURE_SEARCH_SERVICE_ENDPOINT 
        - name: AZURE_SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: AZURE_SEARCH_API_KEY  # UPDATE THIS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oversea-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oversea-client
  template:
    metadata:
      labels:
        app: oversea-client
    spec:
      containers:
      - name: client
        image: us-west1-docker.pkg.dev/cs144-25s-jlin18/oversea-app/oversea-client:v1
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: VITE_API_URL # Change to domain after
        - name: VITE_AI_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: VITE_AI_SERVICE_URL # Change to domain after
        - name: VITE_GEOLOCATION_KEY
          valueFrom:
            secretKeyRef:
              name: oversea-secrets
              key: VITE_GEOLOCATION_KEY