apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: oversea-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: "301"
  sslPolicy: "oversea-ssl-policy"  # Optional: remove if you don't have SSL policy