apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oversea-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "oversea-ip"  # Optional: reserve static IP
    networking.gke.io/managed-certificates: "oversea-certificate"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
spec:
  rules:
    - host: team4.cs144.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oversea-service
                port:
                  number: 80