apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: oversea-server-service
spec:
  selector:
    app: oversea-server
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata: 
  name: oversea-ai-service-service
spec: 
  selector:
    app: oversea-client
  ports:
  - port: 80
    targetPort: 5173
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: oversea-client-service
spec:
  selector:
    app: oversea-client
  ports:
  - port: 80
    targetPort: 5173
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP for Ingress