FROM node:23-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install all dependencies (including devDependencies for nodemon)
RUN npm install 

EXPOSE 3000

# Use nodemon for development
CMD ["npm", "run", "dev"]