name: Deploy Project

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: 
      image: node:23
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 23
      - run: npm ci  
      - run: npm run build