name: Test Project

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    container:
      image: node:23
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "23"
          cache: "npm"

      - name: List directory contents
        run: |
          pwd
          ls -la
          echo "Current directory: $PWD"

      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          npm ci

      - name: Run tests
        run: |
          cd $GITHUB_WORKSPACE
          npm test

      - name: Build project
        run: |
          cd $GITHUB_WORKSPACE
          npm run build
